# Runs the Gradle build action and uploads a coverage report to codecov.io

name: build

on:
  push:
    branches: [ main ]

  # Allow this workflow to be run manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run Gradle tasks
        run: ./gradlew build koverXmlReport --rerun-tasks

      - name: Upload Codecov report
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: ./build/reports/kover/report.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
